elasticsearch-client:
  enabled: true
  clusterName: "elasticsearch-oss"
  nodeGroup: "client"
  roles:
    master: "false"
    ingest: "false"
    data: "false"
    remote_cluster_client: "true"
  image: docker.elastic.co/elasticsearch/elasticsearch-oss
  imageTag: 7.9.3
  replicas: 1
  masterService: "elasticsearch-oss-master"
elasticsearch-master:
  enabled: true
  clusterName: "elasticsearch-oss"
  nodeGroup: "master"
  roles:
    master: "true"
    ingest: "false"
    data: "false"
    remote_cluster_client: "true"
  image: docker.elastic.co/elasticsearch/elasticsearch-oss
  imageTag: 7.9.3
elasticsearch-data:
  enabled: false
  clusterName: "elasticsearch-oss"
  nodeGroup: "data"
  roles:
    master: "false"
    ingest: "false"
    data: "true"
    remote_cluster_client: "true"
  image: docker.elastic.co/elasticsearch/elasticsearch-oss
  imageTag: 7.9.3
  masterService: "elasticsearch-oss-master"
elasticsearch-ingest:
  enabled: false
  clusterName: "elasticsearch-oss"
  nodeGroup: "ingest"
  roles:
    master: "false"
    ingest: "true"
    data: "false"
    remote_cluster_client: "true"
  image: docker.elastic.co/elasticsearch/elasticsearch-oss
  imageTag: 7.9.3
  masterService: "elasticsearch-oss-master"
